export const MERCHANTS = [
  {
    id: "MCH-001",
    business_name: "Almond House",
    contact_name: "Rahul Menon",
    email: "rahul@almondhouse.in",
    phone: "+91 98765 43210",
    city: "Mumbai",
    plan: "Enterprise",
    status: "active",
    joined_date: "2023-04-12",
    monthly_orders: 1240,
    gmv: 48200,
  },
  {
    id: "MCH-002",
    business_name: "The Spice Route",
    contact_name: "Priya Sharma",
    email: "priya@spiceroute.com",
    phone: "+91 91234 56789",
    city: "Delhi",
    plan: "Pro",
    status: "active",
    joined_date: "2023-07-01",
    monthly_orders: 870,
    gmv: 32500,
  },
  {
    id: "MCH-003",
    business_name: "Kochi Crafts",
    contact_name: "Anand Nair",
    email: "anand@kochicrafts.in",
    phone: "+91 94455 66778",
    city: "Kochi",
    plan: "Basic",
    status: "inactive",
    joined_date: "2024-01-15",
    monthly_orders: 120,
    gmv: 4800,
  },
  {
    id: "MCH-004",
    business_name: "Pune Organics",
    contact_name: "Sneha Kulkarni",
    email: "sneha@puneorganics.com",
    phone: "+91 87654 32109",
    city: "Pune",
    plan: "Pro",
    status: "active",
    joined_date: "2023-10-22",
    monthly_orders: 640,
    gmv: 27100,
  },
  {
    id: "MCH-005",
    business_name: "Chennai Textiles",
    contact_name: "Karthik Rajan",
    email: "karthik@chennaitexx.com",
    phone: "+91 99887 76655",
    city: "Chennai",
    plan: "Enterprise",
    status: "active",
    joined_date: "2022-11-08",
    monthly_orders: 2010,
    gmv: 91400,
  },
  {
    id: "MCH-006",
    business_name: "Bengaluru Blooms",
    contact_name: "Divya Reddy",
    email: "divya@bangaloreblooms.in",
    phone: "+91 78901 23456",
    city: "Bengaluru",
    plan: "Basic",
    status: "suspended",
    joined_date: "2024-03-05",
    monthly_orders: 0,
    gmv: 0,
  },
  {
    id: "MCH-007",
    business_name: "Hyderabad Delights",
    contact_name: "Imran Khan",
    email: "imran@hydddelights.com",
    phone: "+91 93344 55566",
    city: "Hyderabad",
    plan: "Pro",
    status: "active",
    joined_date: "2023-08-19",
    monthly_orders: 530,
    gmv: 18700,
  },
  {
    id: "MCH-008",
    business_name: "Jaipur Jewels",
    contact_name: "Meera Joshi",
    email: "meera@jaipurjewels.in",
    phone: "+91 90001 11222",
    city: "Jaipur",
    plan: "Basic",
    status: "active",
    joined_date: "2024-02-28",
    monthly_orders: 310,
    gmv: 52300,
  },
  {
    id: "MCH-009",
    business_name: "Kolkata Confections",
    contact_name: "Sourav Das",
    email: "sourav@kolkatacon.com",
    phone: "+91 82233 44455",
    city: "Kolkata",
    plan: "Pro",
    status: "inactive",
    joined_date: "2023-12-01",
    monthly_orders: 80,
    gmv: 3200,
  },
  {
    id: "MCH-010",
    business_name: "Ahmedabad Auto Parts",
    contact_name: "Ravi Patel",
    email: "ravi@amdauto.in",
    phone: "+91 70000 99888",
    city: "Ahmedabad",
    plan: "Enterprise",
    status: "active",
    joined_date: "2022-06-14",
    monthly_orders: 1680,
    gmv: 135000,
  },
];

export const STATUS_META = {
  active: { label: "Active", color: "#16a34a", bg: "#dcfce7" },
  inactive: { label: "Inactive", color: "#6b7280", bg: "#f3f4f6" },
  suspended: { label: "Suspended", color: "#dc2626", bg: "#fee2e2" },
};

export const PLAN_META = {
  Basic: { color: "#6b7280", bg: "#f3f4f6" },
  Pro: { color: "#2563eb", bg: "#dbeafe" },
  Enterprise: { color: "#7c3aed", bg: "#ede9fe" },
};
